# config.yml

offline-players-tracker:
  enabled: true
  teleport-times:
    position-changed: 1
    position-unchanged: 0

update-checker:
  enabled: true
  period: 36000
  log-after-first-check: true