# config.yml

offline-players-tracker:
  enabled: true
  teleport-times:
    position-changed: 1
    position-unchanged: 0

teleport-when-respawn:
  mark: null
  no-permission-only: false

update-checker:
  enabled: true
  period: 36000
  log-after-first-check: true