name: NWorldPermissions
main: top.nololiyt.worldpermissions.RootPlugin
version: 4.0.4_Pre1
author: yueyinqiu5990
description: A strange power stopping players being teleported to a world.
website: https://github.com/yueyinqiu/NWorldPermissions/wiki
commands:
  nworldpermissions:
    description: "All commands for the plugin 'NWorldPermissions'."
    aliases: [wp,nwp,nwdp,worldpermissions]
