name: NWorldPermissions
description: A strange power stopping players being teleported to a world.
website: https://github.com/yueyinqiu/NWorldPermissions/wiki

version: '4.80'
author: yueyinqiu5990
main: top.nololiyt.worldpermissions.RootPlugin
softdepend: [PlaceholderAPI,MarksAPI]

commands:
  nworldpermissions:
    description: "All commands for the plugin 'NWorldPermissions'."
    aliases: [wp,nwp,nwdp,worldpermissions]