name: NWorldPermissions
main: top.nololiyt.worldpermissions.RootPlugin
version: 3.1.2_Pre3
author: yueyinqiu5990
commands:
  nworldpermissions:
    description: "All commands for the plugin 'NWorldPermissions'."
    aliases: [wp,nwp,nwdp,worldpermissions]